[project]
name = "datingappsimulation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "loguru>=0.7.3",
    "ruff>=0.9.9",
]

[[tool.uv.index]]
url = "https://artifactory.artelys.com/artifactory/api/pypi/pypi-artelys/simple"
default = true

[dependency-groups]
dev = [
    "ipython>=8.18.1",
    "jupyter>=1.1.1",
]

[[tool.uv.index]]
url = "https://pypi.org/simple/"
